baseURL = "https://lena-chamna.netlify.app/"
title = "Î†àÎÇòÏ∞∏ÎÇò"
copyright = "Copyright ¬© 2020 Lena"
paginate = 2
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
googleAnalytics = "UA-XXXX"
DisqusShortname = ""
theme = "hugo-theme-chunky-poster"
[menu]
   [[menu.main]]
      identifier = "home"
      name = "Home"
      url = "/"
      weight = 10
[taxonomies]
category = "categories"
tag = "tags"
series = "series"
author = "authors"

[params]
author = "Lena"
description = "iOS Developer üë©üèª‚Äçüíª"
homepageImage = "/images/homepage-image.jpg"
share = true
showLanguageSwitcher = false

# Custom CSS and JS. Relative to /static/css and /static/js respectively.
customCSS = []
customJS = []
[params.social]
rss = true
email = "keunnalee@gmail.com"
facebook = "https://www.facebook.com/devlena.lee"
linkedin = "https://linkedin.com"
stack-overflow = "https://stackoverflow.com"
instagram = "https://www.instagram.com/dev_lena_lee"
github = "https://github.com/dev-Lena"
weibo = "https://www.weibo.com"
medium = "https://medium.com"
pinterest = "https://pinterest.com"
reddit = "https://reddit.com"
gitlab = "https://gitlab.com"
mastodon = "https://mastodon.social"
keybase = "https://keybase.io/"
[params.prismJS]
   enable = true
   theme = "okaidia"
[params.commento]
   enable = true
   url = "https://commento.io"
[markup]
   [markup.highlight]
      codeFences = false
[services]
   [services.instagram]
      disableInlineCSS = true
   [services.twitter]
      disableInlineCSS = true