baseURL = "https://lena-chamna.netlify.app/"
title = "ë ˆë‚˜ì°¸ë‚˜"
copyright = "Copyright Â© 2020 Lena"
paginate = 2
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
googleAnalytics = "UA-181076923-1"
DisqusShortname = ""
theme = "hugo-theme-chunky-poster"
[menu]
   [[menu.main]]
      identifier = "home"
      name = "Home"
      url = "/"
      weight = 10
[taxonomies]
category = "categories"
tag = "tags"
series = "series"
author = "authors"

[params]
author = "Lena"
description = "iOS Developer ğŸ‘©ğŸ»â€ğŸ’»"
homepageImage = "/images/homepage-image.png"
share = true
showLanguageSwitcher = false

[outputs] 
home = ["HTML", "RSS", "JSON"]
enableRobotsTXT = false

[sitemap] 
changefreq = "weekly" 
filename = "sitemap.xml"

# Custom CSS and JS. Relative to /static/css and /static/js respectively.
customCSS = []
customJS = []
[params.social]
rss = true
email = "keunnalee@gmail.com"
facebook = "https://www.facebook.com/devlena.lee"
linkedin = "https://linkedin.com"
instagram = "https://www.instagram.com/dev_lena_lee"
github = "https://github.com/dev-Lena"
medium = "https://medium.com"
[params.prismJS]
   enable = true
   theme = "okaidia"
[params.commento]
   enable = true
   url = "https://commento.io"
[markup]
   [markup.highlight]
      codeFences = false
[services]
   [services.instagram]
      disableInlineCSS = true
   [services.twitter]
      disableInlineCSS = true